// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUAObN3fZiiLEvtLXhsg0mfkwAKEObNQ',
    appId: '1:683187959687:web:8a10b0ebfb893dd85e8522',
    messagingSenderId: '683187959687',
    projectId: 'phoneauth-b44ef',
    authDomain: 'phoneauth-b44ef.firebaseapp.com',
    storageBucket: 'phoneauth-b44ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC62HFnhqsZX0nFzyH8jo2tb5GIPSFF8oc',
    appId: '1:683187959687:android:2e603a326460c6f15e8522',
    messagingSenderId: '683187959687',
    projectId: 'phoneauth-b44ef',
    storageBucket: 'phoneauth-b44ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsnDXJOAfv_Pjp1j_m5Az3afnlpTfjlA',
    appId: '1:683187959687:ios:a71d2d5395c9a4925e8522',
    messagingSenderId: '683187959687',
    projectId: 'phoneauth-b44ef',
    storageBucket: 'phoneauth-b44ef.appspot.com',
    iosBundleId: 'com.example.blocStateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsnDXJOAfv_Pjp1j_m5Az3afnlpTfjlA',
    appId: '1:683187959687:ios:753fbab74e2aa83d5e8522',
    messagingSenderId: '683187959687',
    projectId: 'phoneauth-b44ef',
    storageBucket: 'phoneauth-b44ef.appspot.com',
    iosBundleId: 'com.example.blocStateManagement.RunnerTests',
  );
}
